"""phase2_add_station_device_ledger_stocktake_adjustment

Revision ID: 9d008cb2ab28
Revises: 9fde5cf8e567
Create Date: 2026-09-11 18:03:01.781690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d008cb2ab28'
down_revision = '9fde5cf8e567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='场站ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='场站名称'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='关联客户'),
    sa.Column('address', sa.Text(), nullable=True, comment='场站地址'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ACTIVE/INACTIVE'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_station_status'), 'station', ['status'], unique=False)
    op.create_table('stocktake',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='盘点ID'),
    sa.Column('stocktake_no', sa.String(length=30), nullable=False, comment='PD前缀盘点单号'),
    sa.Column('mode', sa.String(length=10), nullable=False, comment='CYCLE/FULL'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='进行中/已完成/已取消'),
    sa.Column('warehouse', sa.String(length=30), nullable=False, comment='盘点仓库范围'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktake_status'), 'stocktake', ['status'], unique=False)
    op.create_index(op.f('ix_stocktake_stocktake_no'), 'stocktake', ['stocktake_no'], unique=True)
    op.create_table('device_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='台账ID'),
    sa.Column('item_sn', sa.String(length=50), nullable=False, comment='设备SN，关联inventory_item.item_sn'),
    sa.Column('station_id', sa.Integer(), nullable=False, comment='场站'),
    sa.Column('installed_date', sa.Date(), nullable=False, comment='安装到场站日期'),
    sa.Column('removed_date', sa.Date(), nullable=True, comment='移除日期，NULL=当前在场站'),
    sa.Column('warranty_start', sa.Date(), nullable=True, comment='质保起始日期'),
    sa.Column('warranty_end', sa.Date(), nullable=True, comment='质保到期日期'),
    sa.Column('software_version', sa.String(length=50), nullable=True, comment='软件版本号'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='运行中/故障/已回收'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_ledger_item_sn'), 'device_ledger', ['item_sn'], unique=False)
    op.create_index(op.f('ix_device_ledger_status'), 'device_ledger', ['status'], unique=False)
    op.create_table('stocktake_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='明细ID'),
    sa.Column('stocktake_id', sa.Integer(), nullable=False, comment='盘点任务ID'),
    sa.Column('item_sn', sa.String(length=50), nullable=False, comment='设备SN'),
    sa.Column('sku_id', sa.Integer(), nullable=False, comment='SKU ID'),
    sa.Column('system_qty', sa.Integer(), nullable=False, comment='系统数量'),
    sa.Column('actual_qty', sa.Integer(), nullable=False, comment='实盘数量'),
    sa.Column('diff_qty', sa.Integer(), nullable=False, comment='差异数量'),
    sa.Column('diff_reason', sa.String(length=255), nullable=True, comment='差异原因'),
    sa.Column('scanned_at', sa.DateTime(), nullable=True, comment='扫码时间'),
    sa.Column('scanned_by', sa.Integer(), nullable=True, comment='扫码人'),
    sa.ForeignKeyConstraint(['scanned_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_sku.id'], ),
    sa.ForeignKeyConstraint(['stocktake_id'], ['stocktake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktake_line_item_sn'), 'stocktake_line', ['item_sn'], unique=False)
    op.create_index(op.f('ix_stocktake_line_stocktake_id'), 'stocktake_line', ['stocktake_id'], unique=False)
    op.create_table('inventory_adjustment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='调整ID'),
    sa.Column('adjustment_no', sa.String(length=30), nullable=False, comment='TZ前缀调整单号'),
    sa.Column('stocktake_id', sa.Integer(), nullable=False, comment='盘点任务ID'),
    sa.Column('stocktake_line_id', sa.Integer(), nullable=False, comment='盘点明细ID'),
    sa.Column('item_sn', sa.String(length=50), nullable=False, comment='设备SN'),
    sa.Column('adjustment_type', sa.String(length=10), nullable=False, comment='SURPLUS/SHORTAGE'),
    sa.Column('before_status', sa.String(length=30), nullable=False, comment='调整前库存状态'),
    sa.Column('after_status', sa.String(length=30), nullable=False, comment='调整后库存状态'),
    sa.Column('reason', sa.Text(), nullable=False, comment='调整原因'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['stocktake_id'], ['stocktake.id'], ),
    sa.ForeignKeyConstraint(['stocktake_line_id'], ['stocktake_line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_adjustment_adjustment_no'), 'inventory_adjustment', ['adjustment_no'], unique=True)
    op.drop_constraint('incoming_inspection_ibfk_1', 'incoming_inspection', type_='foreignkey')
    op.drop_constraint('incoming_inspection_ibfk_2', 'incoming_inspection', type_='foreignkey')
    op.drop_index(op.f('ix_incoming_inspection_inspection_no'), table_name='incoming_inspection')
    op.drop_index(op.f('ix_incoming_inspection_receipt_id'), table_name='incoming_inspection')
    op.drop_table('incoming_inspection')
    op.drop_constraint('raw_material_sn_ibfk_1', 'raw_material_sn', type_='foreignkey')
    op.drop_index(op.f('ix_raw_material_sn_inventory_id'), table_name='raw_material_sn')
    op.drop_index(op.f('ix_raw_material_sn_sn'), table_name='raw_material_sn')
    op.drop_table('raw_material_sn')
    op.drop_constraint('incoming_receipt_ibfk_1', 'incoming_receipt', type_='foreignkey')
    op.drop_constraint('incoming_receipt_ibfk_2', 'incoming_receipt', type_='foreignkey')
    op.drop_index(op.f('ix_incoming_receipt_receipt_no'), table_name='incoming_receipt')
    op.drop_index(op.f('ix_incoming_receipt_sku_id'), table_name='incoming_receipt')
    op.drop_index(op.f('ix_incoming_receipt_status'), table_name='incoming_receipt')
    op.drop_index(op.f('ix_incoming_receipt_supplier_id'), table_name='incoming_receipt')
    op.drop_table('incoming_receipt')
    op.drop_constraint('raw_material_inventory_ibfk_1', 'raw_material_inventory', type_='foreignkey')
    op.drop_constraint('raw_material_inventory_ibfk_2', 'raw_material_inventory', type_='foreignkey')
    op.drop_index(op.f('ix_raw_material_inventory_batch_no'), table_name='raw_material_inventory')
    op.drop_index(op.f('ix_raw_material_inventory_sku_id'), table_name='raw_material_inventory')
    op.drop_index(op.f('ix_raw_material_inventory_supplier_id'), table_name='raw_material_inventory')
    op.drop_table('raw_material_inventory')
    op.drop_constraint('raw_material_inventory_log_ibfk_1', 'raw_material_inventory_log', type_='foreignkey')
    op.drop_index(op.f('ix_raw_material_inventory_log_inventory_id'), table_name='raw_material_inventory_log')
    op.drop_table('raw_material_inventory_log')
    op.drop_constraint('incoming_return_ibfk_1', 'incoming_return', type_='foreignkey')
    op.drop_index(op.f('ix_incoming_return_receipt_id'), table_name='incoming_return')
    op.drop_index(op.f('ix_incoming_return_return_no'), table_name='incoming_return')
    op.drop_table('incoming_return')
    op.alter_column('bom_detail', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bom_detail', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('bom_detail_ibfk_1'), 'bom_detail', type_='foreignkey')
    op.create_foreign_key(None, 'bom_detail', 'bom_header', ['bom_id'], ['id'])
    op.alter_column('bom_header', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='状态：草稿/已发布/已停产',
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'"))
    op.alter_column('bom_header', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bom_header', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('bom_no'), table_name='bom_header')
    op.drop_index(op.f('ix_bom_header_bom_no'), table_name='bom_header')
    op.create_index(op.f('ix_bom_header_bom_no'), 'bom_header', ['bom_no'], unique=True)
    op.create_foreign_key(None, 'bom_header', 'product_sku', ['product_sku_id'], ['id'])
    op.add_column('customer', sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'))
    op.add_column('customer', sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'))
    op.add_column('customer', sa.Column('contact_email', sa.String(length=100), nullable=True, comment='邮箱'))
    op.add_column('customer', sa.Column('address', sa.Text(), nullable=True, comment='地址'))
    op.add_column('customer', sa.Column('contract_no', sa.String(length=50), nullable=True, comment='合同编号'))
    op.add_column('customer', sa.Column('contract_start', sa.Date(), nullable=True, comment='合同起始日期'))
    op.add_column('customer', sa.Column('contract_end', sa.Date(), nullable=True, comment='合同到期日期'))
    op.add_column('customer', sa.Column('remark', sa.Text(), nullable=True, comment='备注'))
    op.drop_index(op.f('snapshot_date'), table_name='inventory_daily_summary')
    op.add_column('inventory_item', sa.Column('warehouse_type', sa.String(length=30), nullable=False, comment='仓库类型'))
    op.create_index(op.f('ix_inventory_item_warehouse_type'), 'inventory_item', ['warehouse_type'], unique=False)
    op.alter_column('inventory_item_history', 'event_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='INBOUND/OUTBOUND/STATUS_CHANGE/STOCKTAKE_ADJUST',
               existing_comment='INBOUND/OUTBOUND/STATUS_CHANGE',
               existing_nullable=False)
    op.add_column('inventory_item_snapshot', sa.Column('warehouse_type', sa.String(length=30), nullable=True, comment='仓库类型'))
    op.drop_index(op.f('ix_inventory_item_snapshot_date_type'), table_name='inventory_item_snapshot')
    op.alter_column('inventory_sku_daily_ledger', 'inbound_new',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-正常',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_sale',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-线上售出退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_sold_offline',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-线下售出退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_presold',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-准售出退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_gift',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-赠送退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_scrapped',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-损毁退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_rnd',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-研发退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_sample',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-样机退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_trial',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-试用退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_repair',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入库-维修退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_sold',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-售出-线上',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_sold_offline',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-售出-线下',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_presold',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-准售出',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_gifted',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-赠送',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_scrapped',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-损毁',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_rnd',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-研发',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_sample',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-样机',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_trial',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-试用',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_repair',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-维修',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_borrowed',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出库-借用',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_inventory_sku_daily_ledger_sku_id'), 'inventory_sku_daily_ledger', ['sku_id'], unique=False)
    op.alter_column('outbound_order', 'outbound_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='出库类型',
               existing_comment='SOLD/BORROWED/GIFTED/SCRAPPED',
               existing_nullable=False)
    op.alter_column('product_sku', 'sku_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='物料类型：RAW_MATERIAL/FINISHED_GOODS',
               existing_comment='物料类型',
               existing_nullable=False,
               existing_server_default=sa.text("'FINISHED_GOODS'"))
    op.add_column('production_task', sa.Column('product_type', sa.String(length=30), nullable=False, comment='产出类型：FINISHED_PRODUCT/SEMI_FINISHED'))
    op.alter_column('production_task', 'material_availability',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='齐套/缺料/已齐套',
               existing_comment='齐套状态',
               existing_nullable=False,
               existing_server_default=sa.text("'SHORTAGE'"))
    op.alter_column('production_task', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='待生产/生产中/已完成',
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('production_task', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('production_task', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('task_no'), table_name='production_task')
    op.drop_index(op.f('ix_production_task_task_no'), table_name='production_task')
    op.create_index(op.f('ix_production_task_task_no'), 'production_task', ['task_no'], unique=True)
    op.drop_constraint(op.f('production_task_ibfk_1'), 'production_task', type_='foreignkey')
    op.create_foreign_key(None, 'production_task', 'bom_header', ['bom_id'], ['id'])
    op.alter_column('rma_diagnosis', 'diagnosis_result',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='诊断结果：REPAIRABLE / SCRAP / DIRECT_RESHIP',
               existing_comment='诊断结果',
               existing_nullable=False)
    op.alter_column('rma_repair', 'new_sn',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='新设备 SN（换码时填写）',
               existing_comment='新设备 SN',
               existing_nullable=True)
    op.alter_column('shipment', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('shipment', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('shipment_no'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_shipment_no'), table_name='shipment')
    op.create_index(op.f('ix_shipment_shipment_no'), 'shipment', ['shipment_no'], unique=True)
    op.drop_index(op.f('key'), table_name='sys_config')
    op.drop_index(op.f('ix_sys_config_key'), table_name='sys_config')
    op.create_index(op.f('ix_sys_config_key'), 'sys_config', ['key'], unique=True)
    op.alter_column('sys_user', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='角色：ADMIN/WAREHOUSE/QUALITY/PRODUCTION/TEST_ENGINEER/STAFF',
               existing_comment='角色：ADMIN/STAFF',
               existing_nullable=False,
               existing_server_default=sa.text("'STAFF'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='角色：ADMIN/STAFF',
               existing_comment='角色：ADMIN/WAREHOUSE/QUALITY/PRODUCTION/TEST_ENGINEER/STAFF',
               existing_nullable=False,
               existing_server_default=sa.text("'STAFF'"))
    op.drop_index(op.f('ix_sys_config_key'), table_name='sys_config')
    op.create_index(op.f('ix_sys_config_key'), 'sys_config', ['key'], unique=False)
    op.create_index(op.f('key'), 'sys_config', ['key'], unique=True)
    op.drop_index(op.f('ix_shipment_shipment_no'), table_name='shipment')
    op.create_index(op.f('ix_shipment_shipment_no'), 'shipment', ['shipment_no'], unique=False)
    op.create_index(op.f('shipment_no'), 'shipment', ['shipment_no'], unique=True)
    op.alter_column('shipment', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('shipment', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rma_repair', 'new_sn',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='新设备 SN',
               existing_comment='新设备 SN（换码时填写）',
               existing_nullable=True)
    op.alter_column('rma_diagnosis', 'diagnosis_result',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='诊断结果',
               existing_comment='诊断结果：REPAIRABLE / SCRAP / DIRECT_RESHIP',
               existing_nullable=False)
    op.drop_constraint(None, 'production_task', type_='foreignkey')
    op.create_foreign_key(op.f('production_task_ibfk_1'), 'production_task', 'bom_header', ['bom_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_production_task_task_no'), table_name='production_task')
    op.create_index(op.f('ix_production_task_task_no'), 'production_task', ['task_no'], unique=False)
    op.create_index(op.f('task_no'), 'production_task', ['task_no'], unique=True)
    op.alter_column('production_task', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('production_task', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('production_task', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='状态',
               existing_comment='待生产/生产中/已完成',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('production_task', 'material_availability',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='齐套状态',
               existing_comment='齐套/缺料/已齐套',
               existing_nullable=False,
               existing_server_default=sa.text("'SHORTAGE'"))
    op.drop_column('production_task', 'product_type')
    op.alter_column('product_sku', 'sku_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='物料类型',
               existing_comment='物料类型：RAW_MATERIAL/FINISHED_GOODS',
               existing_nullable=False,
               existing_server_default=sa.text("'FINISHED_GOODS'"))
    op.alter_column('outbound_order', 'outbound_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='SOLD/BORROWED/GIFTED/SCRAPPED',
               existing_comment='出库类型',
               existing_nullable=False)
    op.drop_index(op.f('ix_inventory_sku_daily_ledger_sku_id'), table_name='inventory_sku_daily_ledger')
    op.alter_column('inventory_sku_daily_ledger', 'outbound_borrowed',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-借用',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_repair',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-维修',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_trial',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-试用',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_sample',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-样机',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_rnd',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-研发',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_scrapped',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-损毁',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_gifted',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-赠送',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_presold',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-准售出',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_sold_offline',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-售出-线下',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'outbound_sold',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出库-售出-线上',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_repair',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-维修退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_trial',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-试用退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_sample',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-样机退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_rnd',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-研发退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_scrapped',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-损毁退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_gift',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-赠送退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_presold',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-准售出退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_sold_offline',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-线下售出退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_returned_from_sale',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-线上售出退回',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('inventory_sku_daily_ledger', 'inbound_new',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入库-正常',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_inventory_item_snapshot_date_type'), 'inventory_item_snapshot', ['snapshot_date', 'snapshot_type'], unique=False)
    op.drop_column('inventory_item_snapshot', 'warehouse_type')
    op.alter_column('inventory_item_history', 'event_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='INBOUND/OUTBOUND/STATUS_CHANGE',
               existing_comment='INBOUND/OUTBOUND/STATUS_CHANGE/STOCKTAKE_ADJUST',
               existing_nullable=False)
    op.drop_index(op.f('ix_inventory_item_warehouse_type'), table_name='inventory_item')
    op.drop_column('inventory_item', 'warehouse_type')
    op.create_index(op.f('snapshot_date'), 'inventory_daily_summary', ['snapshot_date'], unique=True)
    op.drop_column('customer', 'remark')
    op.drop_column('customer', 'contract_end')
    op.drop_column('customer', 'contract_start')
    op.drop_column('customer', 'contract_no')
    op.drop_column('customer', 'address')
    op.drop_column('customer', 'contact_email')
    op.drop_column('customer', 'contact_phone')
    op.drop_column('customer', 'contact_person')
    op.drop_constraint(None, 'bom_header', type_='foreignkey')
    op.drop_index(op.f('ix_bom_header_bom_no'), table_name='bom_header')
    op.create_index(op.f('ix_bom_header_bom_no'), 'bom_header', ['bom_no'], unique=False)
    op.create_index(op.f('bom_no'), 'bom_header', ['bom_no'], unique=True)
    op.alter_column('bom_header', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('bom_header', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bom_header', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='状态',
               existing_comment='状态：草稿/已发布/已停产',
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'"))
    op.drop_constraint(None, 'bom_detail', type_='foreignkey')
    op.create_foreign_key(op.f('bom_detail_ibfk_1'), 'bom_detail', 'bom_header', ['bom_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bom_detail', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('bom_detail', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('incoming_return',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('receipt_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='到货单 ID'),
    sa.Column('return_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='退货单号'),
    sa.Column('return_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='退货数量'),
    sa.Column('return_reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='退货原因'),
    sa.Column('return_date', sa.DATE(), nullable=False, comment='退货日期'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'PENDING'"), nullable=False, comment='PENDING / CONFIRMED'),
    sa.Column('operator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='操作人 ID'),
    sa.Column('change_reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='变更原因'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='备注'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_user.id'], name=op.f('incoming_return_ibfk_2')),
    sa.ForeignKeyConstraint(['receipt_id'], ['incoming_receipt.id'], name=op.f('incoming_return_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_incoming_return_return_no'), 'incoming_return', ['return_no'], unique=True)
    op.create_index(op.f('ix_incoming_return_receipt_id'), 'incoming_return', ['receipt_id'], unique=False)
    op.create_table('raw_material_inventory_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('inventory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='库存批次 ID'),
    sa.Column('sn_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='SN ID（按 SN 扣减时记录）'),
    sa.Column('change_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='INCREASE / DECREASE'),
    sa.Column('change_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='变更数量'),
    sa.Column('before_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='变更前数量'),
    sa.Column('after_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='变更后数量'),
    sa.Column('change_reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='变更原因'),
    sa.Column('related_order_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='关联单号'),
    sa.Column('operator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='操作人 ID'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='备注'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['inventory_id'], ['raw_material_inventory.id'], name=op.f('raw_material_inventory_log_ibfk_1')),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_user.id'], name=op.f('raw_material_inventory_log_ibfk_3')),
    sa.ForeignKeyConstraint(['sn_id'], ['raw_material_sn.id'], name=op.f('raw_material_inventory_log_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_raw_material_inventory_log_inventory_id'), 'raw_material_inventory_log', ['inventory_id'], unique=False)
    op.create_table('raw_material_inventory',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sku_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='物料 SKU ID'),
    sa.Column('batch_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='批次号'),
    sa.Column('quantity', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='库存数量'),
    sa.Column('unit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'个'"), nullable=False, comment='单位'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'IN_STOCK'"), nullable=False, comment='库存状态'),
    sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='供应商 ID'),
    sa.Column('receipt_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='关联到货单号'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='备注'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_sku.id'], name=op.f('raw_material_inventory_ibfk_1')),
    sa.ForeignKeyConstraint(['supplier_id'], ['partner.id'], name=op.f('raw_material_inventory_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_raw_material_inventory_supplier_id'), 'raw_material_inventory', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_raw_material_inventory_sku_id'), 'raw_material_inventory', ['sku_id'], unique=False)
    op.create_index(op.f('ix_raw_material_inventory_batch_no'), 'raw_material_inventory', ['batch_no'], unique=False)
    op.create_table('incoming_receipt',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('receipt_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='到货单号'),
    sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='供应商 ID'),
    sa.Column('sku_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='物料 SKU ID'),
    sa.Column('batch_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='批次号'),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='到货数量'),
    sa.Column('unit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'个'"), nullable=False, comment='单位'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), server_default=sa.text("'PENDING_INSPECTION'"), nullable=False, comment='状态'),
    sa.Column('delivery_date', sa.DATE(), nullable=False, comment='到货日期'),
    sa.Column('inspector_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='检验人 ID'),
    sa.Column('inspection_date', sa.DATE(), nullable=True, comment='检验日期'),
    sa.Column('change_reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='变更原因'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='备注'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('confirmed_at', mysql.DATETIME(), nullable=True, comment='入库确认时间'),
    sa.Column('confirmed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='入库确认人 ID'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['sys_user.id'], name=op.f('fk_incoming_receipt_confirmed_by')),
    sa.ForeignKeyConstraint(['inspector_id'], ['sys_user.id'], name=op.f('incoming_receipt_ibfk_3')),
    sa.ForeignKeyConstraint(['sku_id'], ['product_sku.id'], name=op.f('incoming_receipt_ibfk_2')),
    sa.ForeignKeyConstraint(['supplier_id'], ['partner.id'], name=op.f('incoming_receipt_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_incoming_receipt_supplier_id'), 'incoming_receipt', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_incoming_receipt_status'), 'incoming_receipt', ['status'], unique=False)
    op.create_index(op.f('ix_incoming_receipt_sku_id'), 'incoming_receipt', ['sku_id'], unique=False)
    op.create_index(op.f('ix_incoming_receipt_receipt_no'), 'incoming_receipt', ['receipt_no'], unique=True)
    op.create_table('raw_material_sn',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('inventory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='库存批次 ID'),
    sa.Column('sn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='原材料 SN 号'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'IN_STOCK'"), nullable=False, comment='SN 状态'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='备注'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['inventory_id'], ['raw_material_inventory.id'], name=op.f('raw_material_sn_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_raw_material_sn_sn'), 'raw_material_sn', ['sn'], unique=False)
    op.create_index(op.f('ix_raw_material_sn_inventory_id'), 'raw_material_sn', ['inventory_id'], unique=False)
    op.create_table('incoming_inspection',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('receipt_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='到货单 ID'),
    sa.Column('inspection_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='检验编号'),
    sa.Column('inspector_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='检验人 ID'),
    sa.Column('inspection_date', sa.DATE(), nullable=False, comment='检验日期'),
    sa.Column('result', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False, comment='ACCEPTED / CONCESSION_ACCEPTED / REJECTED'),
    sa.Column('sample_qty', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='抽样数量'),
    sa.Column('defect_qty', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='不良数量'),
    sa.Column('defect_description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='不良描述'),
    sa.Column('change_reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='变更原因'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='备注'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['inspector_id'], ['sys_user.id'], name=op.f('incoming_inspection_ibfk_2')),
    sa.ForeignKeyConstraint(['receipt_id'], ['incoming_receipt.id'], name=op.f('incoming_inspection_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_incoming_inspection_receipt_id'), 'incoming_inspection', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_incoming_inspection_inspection_no'), 'incoming_inspection', ['inspection_no'], unique=True)
    op.drop_index(op.f('ix_inventory_adjustment_adjustment_no'), table_name='inventory_adjustment')
    op.drop_table('inventory_adjustment')
    op.drop_index(op.f('ix_stocktake_line_stocktake_id'), table_name='stocktake_line')
    op.drop_index(op.f('ix_stocktake_line_item_sn'), table_name='stocktake_line')
    op.drop_table('stocktake_line')
    op.drop_index(op.f('ix_device_ledger_status'), table_name='device_ledger')
    op.drop_index(op.f('ix_device_ledger_item_sn'), table_name='device_ledger')
    op.drop_table('device_ledger')
    op.drop_index(op.f('ix_stocktake_stocktake_no'), table_name='stocktake')
    op.drop_index(op.f('ix_stocktake_status'), table_name='stocktake')
    op.drop_table('stocktake')
    op.drop_index(op.f('ix_station_status'), table_name='station')
    op.drop_table('station')
    # ### end Alembic commands ###