"""add_all_business_tables

Revision ID: a43f9ddeab1a
Revises: db50005be6c8
Create Date: 2026-06-08 17:43:13.029582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43f9ddeab1a'
down_revision = 'db50005be6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False, comment='快照时间'),
    sa.Column('item_id', sa.BigInteger(), nullable=False, comment='原单品ID'),
    sa.Column('item_sn', sa.String(length=50), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('stock_status', sa.String(length=30), nullable=False),
    sa.Column('stock_condition', sa.String(length=30), nullable=False),
    sa.Column('operation_status', sa.String(length=30), nullable=False),
    sa.Column('last_order_no', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_snapshot_item_sn'), 'inventory_item_snapshot', ['item_sn'], unique=False)
    op.create_index(op.f('ix_inventory_item_snapshot_snapshot_at'), 'inventory_item_snapshot', ['snapshot_at'], unique=False)
    op.create_table('partner_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='分组ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分组名称'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='分类ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sys_enum',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='枚举分类'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='枚举代码'),
    sa.Column('label', sa.String(length=100), nullable=False, comment='展示名称'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('enabled', sa.SmallInteger(), nullable=False, comment='1=启用 0=禁用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'code', name='uk_enum_category_code')
    )
    op.create_index(op.f('ix_sys_enum_category'), 'sys_enum', ['category'], unique=False)
    op.create_table('sys_sequence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seq_type', sa.String(length=10), nullable=False, comment='序列类型：JIN / JOUT'),
    sa.Column('seq_date', sa.String(length=8), nullable=False, comment='日期 YYYYMMDD'),
    sa.Column('current_value', sa.Integer(), nullable=False, comment='当前序号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq_type', 'seq_date', name='uk_seq_type_date')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='单位ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='单位名称'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='分组ID'),
    sa.Column('partner_type', sa.SmallInteger(), nullable=False, comment='0=供应商&客户 1=客户 2=供应商'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=启用 0=停用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['group_id'], ['partner_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_group_id'), 'partner', ['group_id'], unique=False)
    op.create_table('product_sku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='商品ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='商品名称'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='分类ID'),
    sa.Column('barcode', sa.String(length=50), nullable=False, comment='条码编码，如 NO00001'),
    sa.Column('sn_mode', sa.String(length=10), nullable=False, comment='SN模式：MANUAL/AUTO/BOTH'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=启用 0=停用'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index(op.f('ix_product_sku_category_id'), 'product_sku', ['category_id'], unique=False)
    op.create_table('inventory_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_sn', sa.String(length=50), nullable=False, comment='Item SN'),
    sa.Column('sku_id', sa.Integer(), nullable=False, comment='SKU ID'),
    sa.Column('stock_status', sa.String(length=30), nullable=False, comment='库存状态'),
    sa.Column('stock_condition', sa.String(length=30), nullable=False, comment='库存属性'),
    sa.Column('operation_status', sa.String(length=30), nullable=False, comment='操作状态'),
    sa.Column('last_order_no', sa.String(length=30), nullable=True, comment='最近关联单号'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量，固定为1'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_item_sn'), 'inventory_item', ['item_sn'], unique=True)
    op.create_index(op.f('ix_inventory_item_sku_id'), 'inventory_item', ['sku_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_stock_status'), 'inventory_item', ['stock_status'], unique=False)
    op.create_table('outbound_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=False, comment='JOUT-单号'),
    sa.Column('outbound_type', sa.String(length=20), nullable=False, comment='SOLD/BORROWED/GIFTED/SCRAPPED'),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('operation_status', sa.String(length=30), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_order_operation_status'), 'outbound_order', ['operation_status'], unique=False)
    op.create_index(op.f('ix_outbound_order_order_no'), 'outbound_order', ['order_no'], unique=True)
    op.create_table('inbound_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=False, comment='JIN-单号'),
    sa.Column('inbound_mode', sa.String(length=20), nullable=False, comment='PROCUREMENT/NON_PROCUREMENT'),
    sa.Column('stock_condition', sa.String(length=30), nullable=False, comment='入库类型/库存属性'),
    sa.Column('partner_id', sa.Integer(), nullable=True, comment='往来单位'),
    sa.Column('related_outbound_order_id', sa.BigInteger(), nullable=True, comment='关联出库单（非采购入库）'),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('operation_status', sa.String(length=30), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False, comment='商品总数量'),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['related_outbound_order_id'], ['outbound_order.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_order_operation_status'), 'inbound_order', ['operation_status'], unique=False)
    op.create_index(op.f('ix_inbound_order_order_no'), 'inbound_order', ['order_no'], unique=True)
    op.create_table('inventory_item_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False, comment='单品ID'),
    sa.Column('event_type', sa.String(length=30), nullable=False, comment='INBOUND/OUTBOUND/STATUS_CHANGE'),
    sa.Column('order_no', sa.String(length=30), nullable=True, comment='关联单号'),
    sa.Column('from_stock_status', sa.String(length=30), nullable=True),
    sa.Column('to_stock_status', sa.String(length=30), nullable=True),
    sa.Column('from_operation_status', sa.String(length=30), nullable=True),
    sa.Column('to_operation_status', sa.String(length=30), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录时间'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_history_item_id'), 'inventory_item_history', ['item_id'], unique=False)
    op.create_table('outbound_order_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('outbound_order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['outbound_order_id'], ['outbound_order.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_order_item_outbound_order_id'), 'outbound_order_item', ['outbound_order_id'], unique=False)
    op.create_table('inbound_order_line',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inbound_order_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='商品数量'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['inbound_order.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_order_line_inbound_order_id'), 'inbound_order_line', ['inbound_order_id'], unique=False)
    op.create_table('inbound_order_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inbound_order_id', sa.BigInteger(), nullable=False),
    sa.Column('line_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('item_sn', sa.String(length=50), nullable=False, comment='录入或生成的SN'),
    sa.Column('sn_source', sa.String(length=10), nullable=False, comment='MANUAL/AUTO'),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['inbound_order.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['inbound_order_line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_order_item_inbound_order_id'), 'inbound_order_item', ['inbound_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inbound_order_item_inbound_order_id'), table_name='inbound_order_item')
    op.drop_table('inbound_order_item')
    op.drop_index(op.f('ix_inbound_order_line_inbound_order_id'), table_name='inbound_order_line')
    op.drop_table('inbound_order_line')
    op.drop_index(op.f('ix_outbound_order_item_outbound_order_id'), table_name='outbound_order_item')
    op.drop_table('outbound_order_item')
    op.drop_index(op.f('ix_inventory_item_history_item_id'), table_name='inventory_item_history')
    op.drop_table('inventory_item_history')
    op.drop_index(op.f('ix_inbound_order_order_no'), table_name='inbound_order')
    op.drop_index(op.f('ix_inbound_order_operation_status'), table_name='inbound_order')
    op.drop_table('inbound_order')
    op.drop_index(op.f('ix_outbound_order_order_no'), table_name='outbound_order')
    op.drop_index(op.f('ix_outbound_order_operation_status'), table_name='outbound_order')
    op.drop_table('outbound_order')
    op.drop_index(op.f('ix_inventory_item_stock_status'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_sku_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_item_sn'), table_name='inventory_item')
    op.drop_table('inventory_item')
    op.drop_index(op.f('ix_product_sku_category_id'), table_name='product_sku')
    op.drop_table('product_sku')
    op.drop_index(op.f('ix_partner_group_id'), table_name='partner')
    op.drop_table('partner')
    op.drop_table('sys_sequence')
    op.drop_index(op.f('ix_sys_enum_category'), table_name='sys_enum')
    op.drop_table('sys_enum')
    op.drop_table('product_category')
    op.drop_table('partner_group')
    op.drop_index(op.f('ix_inventory_item_snapshot_snapshot_at'), table_name='inventory_item_snapshot')
    op.drop_index(op.f('ix_inventory_item_snapshot_item_sn'), table_name='inventory_item_snapshot')
    op.drop_table('inventory_item_snapshot')
    # ### end Alembic commands ###
