"""add unit to product_sku

Revision ID: da1389b468cc
Revises: c8f2a1b3d4e5
Create Date: 2026-06-10 17:43:30.418702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1389b468cc'
down_revision = 'c8f2a1b3d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sku', sa.Column('unit', sa.String(length=20), nullable=True, comment='计量单位，如 个/张/份/副'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sku', 'unit')
    # ### end Alembic commands ###
