"""init sys_user

Revision ID: db50005be6c8
Revises: 
Create Date: 2026-06-08 17:27:38.606335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db50005be6c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='bcrypt 密码哈希'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='显示昵称'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像 URL'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态：1=正常，0=禁用'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_table('sys_user')
    # ### end Alembic commands ###
